{
 "title": "ClickHouse Dashboard",
 "description": "Clickhouse",
 "tags": [
  "clickhouse",
  "operator"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "exported_namespace",
    "label": "K8S Namespace",
    "query": "label_values(ClickHouseAsyncMetrics_Uptime, exported_namespace)"
   },
   {
    "name": "chi",
    "label": "K8S Clickhouse Installation",
    "query": "label_values(ClickHouseAsyncMetrics_Uptime, chi)"
   },
   {
    "name": "hostname",
    "label": "Server",
    "query": "label_values(ClickHouseAsyncMetrics_Uptime, hostname)"
   }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "table",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 0 },
   "targets": [
    { "expr": "ClickHouseAsyncMetrics_Uptime", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "format": "Parrots",
   "valueName": "min",
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{container=\"au-tsdb-clickhouse\"}[5m])*100"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{container=\"au-tsdb-clickhouse\"}"
    }
   ]
  },
  {
   "title": "Version",
   "type": "table",
   "description": "For example, version 11.22.33 is translated to 11022033",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "ClickHouseMetrics_VersionInteger",
     "legendFormat": "Version: {{job}}"
    },
    { "expr": "ClickHouseMetrics_Revision\r", "legendFormat": "Revision {{job}}" }
   ]
  },
  {
   "title": "Jemalloc",
   "type": "graph",
   "description": "Show jemalloc memory distribution",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ClickHouseAsyncMetrics_jemalloc_mapped\r{exported_namespace=~\"[[exported_namespace]]\"}",
     "legendFormat": "mapped {{job}}"
    },
    {
     "expr": "ClickHouseAsyncMetrics_jemalloc_resident\r{exported_namespace=~\"[[exported_namespace]]\"}",
     "legendFormat": "resident {{job}}"
    },
    {
     "expr": "ClickHouseAsyncMetrics_jemalloc_retained\r{exported_namespace=~\"[[exported_namespace]]\"}",
     "legendFormat": "retained {{job}}"
    },
    {
     "expr": "ClickHouseAsyncMetrics_jemalloc_active\r{exported_namespace=~\"[[exported_namespace]]\"}",
     "legendFormat": "active {{job}}"
    },
    {
     "expr": "ClickHouseAsyncMetrics_jemalloc_allocated\r{exported_namespace=~\"[[exported_namespace]]\"}",
     "legendFormat": "allocated {{job}}"
    },
    {
     "expr": "ClickHouseAsyncMetrics_jemalloc_metadata\r{exported_namespace=~\"[[exported_namespace]]\"}",
     "legendFormat": "metadata {{job}}"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "graph",
   "description": "Show different types of connections for each server",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ClickHouseMetrics_TCPConnection{exported_namespace=~\"[[exported_namespace]]\",chi=~\"[[chi]]\",hostname=~\"[[hostname]]\"}",
     "legendFormat": "tcp {{job}}"
    },
    {
     "expr": "ClickHouseMetrics_HTTPConnection{exported_namespace=~\"[[exported_namespace]]\",chi=~\"[[chi]]\",hostname=~\"[[hostname]]\"}",
     "legendFormat": "http {{job}}"
    },
    {
     "expr": "ClickHouseMetrics_InterserverConnection{exported_namespace=~\"[[exported_namespace]]\",chi=~\"[[chi]]\",hostname=~\"[[hostname]]\"}",
     "legendFormat": "interserver {{job}}"
    },
    {
     "expr": "ClickHouseMetrics_MySQLConnection{exported_namespace=~\"[[exported_namespace]]\",chi=~\"[[chi]]\",hostname=~\"[[hostname]]\"}",
     "legendFormat": "mysql {{job}}"
    }
   ]
  },
  {
   "title": "Query",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(ClickHouseProfileEvents_Query\r[1m])",
     "legendFormat": "Query {{job}}"
    },
    {
     "expr": "rate(ClickHouseProfileEvents_SelectQuery\r[1m])",
     "legendFormat": "SelectQuery {{job}}"
    },
    {
     "expr": "rate(ClickHouseProfileEvents_InsertQuery\r[1m])",
     "legendFormat": "InsertQuery {{job}}"
    }
   ]
  },
  {
   "title": "w/r Failed",
   "type": "graph",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(ClickHouseProfileEvents_WriteBufferFromFileDescriptorWriteFailed\r[1m])",
     "legendFormat": "Write Failed by {{job}}"
    },
    {
     "expr": "rate(ClickHouseProfileEvents_ReadBufferFromFileDescriptorReadFailed\r[1m])",
     "legendFormat": "Read Failed by {{job}}"
    }
   ]
  },
  {
   "title": "Page Fault",
   "type": "graph",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(ClickHouseProfileEvents_HardPageFaults[5m])",
     "legendFormat": "Hard by {{job}}"
    },
    {
     "expr": "rate(ClickHouseProfileEvents_SoftPageFaults\r[1m])",
     "legendFormat": "Soft by {{job}}"
    }
   ]
  },
  {
   "title": "Merge",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(ClickHouseProfileEvents_MergedRows[1m])",
     "legendFormat": "MergedRows by {{job}}"
    },
    {
     "expr": "rate(ClickHouseProfileEvents_MergedUncompressedBytes[1m])",
     "legendFormat": "MergedUncompressedBytes by {{job}}"
    }
   ]
  },
  {
   "title": "Compressed Read Buffer",
   "type": "graph",
   "description": "Show how much bytes read and decompress via compressed buffer on each server in cluster",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 11 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(ClickHouseProfileEvents_CompressedReadBufferBytes{exported_namespace=~\"[[exported_namespace]]\",chi=~\"[[chi]]\",hostname=~\"[[hostname]]\"}[1m])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Read Descriptor",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 11 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(ClickHouseProfileEvents_ReadBufferFromFileDescriptorReadBytes\r[1m])",
     "legendFormat": "descriptor bytes by {{job}}"
    },
    {
     "expr": "rate(ClickHouseProfileEvents_ReadBufferFromFileDescriptorRead\r[1m])",
     "legendFormat": "descriptor by {{job}}"
    }
   ]
  },
  {
   "title": "Open Files",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(ClickHouseProfileEvents_FileOpen\r[1m])",
     "legendFormat": "Open files by {{job}}"
    }
   ]
  },
  {
   "title": "Marks Cache Hit Rate",
   "type": "graph",
   "description": "Show which percent of mark files (.mrk) read from memory instead of disk",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 18 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(ClickHouseProfileEvents_MarkCacheHits[1m]) / (rate(ClickHouseProfileEvents_MarkCacheHits[1m]) + rate(ClickHouseProfileEvents_MarkCacheMisses[1m]))",
     "legendFormat": "1m {{job}}"
    }
   ]
  },
  {
   "title": "Write Descriptor",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 18 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(ClickHouseProfileEvents_WriteBufferFromFileDescriptorWriteBytes\r[1m])",
     "legendFormat": "descriptor bytes by {{job}}"
    },
    {
     "expr": "rate(ClickHouseProfileEvents_WriteBufferFromFileDescriptorWrite\r[1m])",
     "legendFormat": "descriptor by {{job}}"
    }
   ]
  }
 ]
}